name: C++ Tensor Library CI

# Tell GitHub when to run this pipeline (when to trigger)
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    # Tell GitHub to use Ubuntu server (set the environment)
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Run CMake (configure)
    - name: Configure CMake
      run: cmake -B build

    # Compile the code (build)
    - name: build
      run: cmake --build build

    # Run GoogleTest (test)
    - name: Run Tests
      working-directory: ./build
      run: ctest --output-on-failure